### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by MaloSparky** [microsoft/ARI#124]
Resource create date.

**Comment by Claudio-Merola** [comment]
Hi @MaloSparky

We added that information for most of the resources already. But many resources don't have that information in the Resource Graph. So the only way to add that to the script would be to complete change the way to extract the data to Rest API, but that would impact performance and the gain would not be so much. That's why we dropped the idea.

**Comment by MaloSparky** [comment]
Thanks, that is what I feared after my research.
