### ISSUE TITLE
ARI generates report after almost 1.5hrs

### ISSUE THREAD

**Issue by Ninsharma** [microsoft/ARI#146]
Hello everyone,

I had been trying to generate ARI report since couple of days now. After lots of troubleshooting steps tried, I am now able to run command "./AzureResourceInventory.ps1" in PS. The output says that an "Excel file" and Drawio" file are saved at default directory i.e., at C:\AzureResourceInventory" however, I am unable to find them. I tried several times running the same command but no luck. Is anyone else experiencing the same issue? Kindly advice. 

Also, around 3 weeks back, generating ARI reports used to take not more than 10mins and now it takes around 93mins. I am trying to understand why is it taking so much time?

**Comment by Claudio-Merola** [comment]
Hello @Ninsharma,

That's odd, the folder C:\AzureResourceInventory is already created? Since you said the script did not created the files, I'm suspecting on permissions, are you running the script as admin?

Also, can you try to run the script adding the parameter "-Debug"? That will give more details on what the script is doing, and what might be the problem.
