### ISSUE TITLE
Resrevations Request

### ISSUE THREAD

**Issue by Juzzi79** [microsoft/ARI#153]
Would it be possible for you to add in Reservations as that would be amazing?

**Comment by Claudio-Merola** [comment]
Hi @Juzzi79

Thanks for using the tool and for the suggestion. 

Actually it is possible, but is not easy. Reservations require a different set of permissions and I believe they would require to be extracted in a different way. Extraction itself should not be the problem, since we already so something similar do Quotas. 

I believe is something we can consider to be included in future versions with some special parameter.
