### ISSUE TITLE
Create diagrams by VNet

### ISSUE THREAD

**Issue by wingcomm** [microsoft/ARI#167]
Any chance we can get diagrams that show connected resources attached by VNet. It would be very useful to have automated diagrams that show how application resources with a mixture of Public IPs and Private Endpoints are connected to a VNet within the same resource group and/or across resource groups.

**Comment by Claudio-Merola** [comment]
Hi @wingcomm 

I don't think I understood that. Can you explain that a little further?

**Comment by Claudio-Merola** [comment]
That is sort of what you already get with the Network Diagram...

https://learn.microsoft.com/en-us/azure/network-watcher/view-network-topology?tabs=portal

This is basically what's inside each box in the diagram, The main box is the VNET, the smaller boxes are the subnets and the resource inside the smaller box is the type of resource most seen inside that specific subnet. 

The only difference is that we are not printing every single resource in the subnet. But this is intentional, imagine printing every single resource of every single subnet for every single VNET...

https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/network-level-segmentation

In the Pattern 4 the main point is to have an overall view of the VNETs and the peerings, and we already have that, specially when using the Hub-Spoke correctly in the environment.
