### ISSUE TITLE
Help add Modules services 

### ISSUE THREAD

**Issue by Weerayug** [microsoft/ARI#198]
Help add Modules services
1.Data factories
2.Azure OpenAI
3.AI Search
Can you give it to us?

**Comment by Claudio-Merola** [comment]
Hello @Weerayug 

I made some new modules for AI, including for AI Search.

But OpenAI is still under development and there isn't much information to create a module for Data Factory. Most of Data Factory data is inside Data Factory Studio, since we can only capture data inside Azure Portal the module would report very little information.
