### ISSUE TITLE
No data in Advisory TAB

### ISSUE THREAD

**Issue by red-erik** [microsoft/ARI#207]
Hello,
it seems that #78 is still present into 3.1.16 and 3.1.38.
We don't see any error but Advisory TAB is empty.

variables passed here seem to be empty

.NOTES
Version: 2.0.0
First Release Date: 19th November, 2020
Authors: Claudio Merola and Renato Gregio 

#>
param($Advisories, $Task ,$File, $Adv, $TableStyle)

Report Complete. Total Runtime was: 11,88 Minutes
Total Resources: 10516
Total Advisories: 0
Total Policies: 20

Regards,
Red.

**Comment by Claudio-Merola** [comment]
Hello @red-erik , I just released the version 3.5. and since we changed a lot of how the script works (it's no longer a script, but a Powershell Module) and we completely remove the need of az cli as we changed 100% to powershell. This might have changed the previous behavior.

Do you mind and give a try to new version so we can validate if this issue is fixed?

Thanks

**Comment by red-erik** [comment]
Hello,
testing on my PC (Windows 11 latest and powershell 7.4.5) as soon as I run invoke-ARI it ask me to logon to Azure than it closes completely the powershell session. Will try from a dedicated server on Windows 2022.

Regards,
Red.

**Comment by red-erik** [comment]
Hello, it works from server Win 2022
