### ISSUE TITLE
AntiVirus (Defender) blocking AzureResourceInventory.ps1

### ISSUE THREAD

**Issue by miked1903** [microsoft/ARI#209]
From the release of v3.1.22, onwards I receive the following

+ ##################################################################### ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This script contains malicious content and has been blocked by your antivirus software.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : ScriptContainedMaliciousContent

If I do a global remove of the change from 3,1,21, removing "(get-date -Format 'yyyy-MM-dd_HH_mm_ss')+' - '+" . The script will run as expected.

Does anybody else see this issue?

**Comment by Claudio-Merola** [comment]
Hello, this is very odd. I really don't see why the AV would complain of date formatting at all.

anyway, I just released the version 3.5 of ARI and since we changed a lot of how the script works (it's no longer a script, but a Powershell Module) and we completely remove the need of az cli as we changed 100% to powershell. This might have changed the previous behavior.

Do you mind and give a try to new version so we can validate how the AV will behave with this version?

Thanks

**Comment by miked1903** [comment]
Hello Claudio, tested and working. And a few bugs I had noted have been corrected too.

thank you for prompt response
