### ISSUE TITLE
No resource data because 'the value of argument "name" is not valid' error

### ISSUE THREAD

**Issue by omarcarpio** [microsoft/ARI#211]
As you may already know there is some strange behavior in Azure Powershell when you use this command: 
Search-AzGraph -Query "resources | where subscriptionId ...." -skip $Limit -first 1000 (old ARI' line 118)

...getting this error: "Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again."

 I used to bypass it just setting the $Limit to 2 or 3, this because some Logic Apps have a huge 'properties' value...so, they're finally exclude and I'm just okay with that!

But now, with this new versión of ARI, where the only line is Invoke-ARI, how can I bypass this issue? Any advice? Thanks

**Comment by Claudio-Merola** [comment]
Hi @omarcarpio ,

Yea, that is an old issue...

Since we don't have a LogicApp module I believe it makes more sense to just exclude that resource type from the capture at all.

You would have to modify line 98 of the file ARIResourceDataPull.psm1.

I intend to do that as a more permanent fix in the next update, but I'll wait for some other fixes before releasing it. So it should take 1 more week before that fix is out.

**Comment by omarcarpio** [comment]
Thanks @Claudio-Merola, meanwhile...is there a way to keep using this old ARI version (3.1.9)? Because now it doesn't work, I'm getting this "The remote server returned an error: (404) Not Found". For what I know the repo URL is down. Thanks

**Comment by Claudio-Merola** [comment]
@omarcarpio 

Yes, you can still access the old files in the repository: 

https://github.com/microsoft/ARI/tree/9c0087dade094fd31744cbd0e379158bdb72460c
